verbose: true
admin_port: "444"
admin_access_port: "444"
local_host: "192.168.1.99"
validation_service_port: "81"
data_directory: "/etc/mtls-gateway"
mtls_id_ttl: 1
device_name: "Prd-Agent"
identity_broker: "identity.plus"
roles_allowed:
  - "org. administrator"
  - "org. manager"
  - "administrator"
  - "manager"
